/* eslint-disable no-magic-numbers */
import antfu from '@antfu/eslint-config'

export default antfu({
  stylistic: false,
  ignores: ['extension/dist/**', 'fixtures/**', 'training/**'],
  rules: {
    'max-depth': ['error', 2],
    'max-params': ['error', 3],
    'max-lines-per-function': ['error', { max: 45, skipBlankLines: true, skipComments: true }],
    'max-lines': ['error', { max: 300, skipBlankLines: true, skipComments: true }],
    'max-statements': ['error', 15],
    'max-nested-callbacks': ['error', 3],
    'complexity': ['error', 10],
    'id-denylist': ['error', 'data', 'result', 'temp', 'info', 'flag', 'item', 'obj', 'arr', 'str', 'num', 'val', 'el', 'idx', 'fn'],
    'id-length': ['error', { min: 2, exceptions: ['i', 'j', 'k', 'x', 'y', 'z', 'u', 'v', 'w', '_', 'id', 'db', 'e'] }],
    'no-param-reassign': 'error',
    'no-useless-catch': 'error',
    'no-restricted-syntax': [
      'error',
      'TSEnumDeclaration[const=true]',
      'TSExportAssignment',
      { selector: 'Literal[value=/\\u2014/]', message: 'Never use emdashes.' },
      { selector: 'TemplateElement[value.raw=/\\u2014/]', message: 'Never use emdashes (do not replace it with -).' },
    ],
    'no-warning-comments': ['error', { terms: ['todo', 'fixme', 'xxx'], location: 'anywhere' }],
    'no-magic-numbers': ['error', {
      ignore: [
        -1,
        0,
        1,
        2,
        7,
        24,
        60,
        100,
        1000,
        10000,
      ],
      ignoreArrayIndexes: true,
      ignoreDefaultValues: true,
      ignoreClassFieldInitialValues: true,
      enforceConst: true,
    }],
    'no-console': ['error', { allow: ['warn', 'error', 'info'] }],
    'no-empty': ['error', { allowEmptyCatch: false }],
    'consistent-return': 'error',
    'unicorn/filename-case': ['error', { cases: { kebabCase: true, camelCase: true, pascalCase: true } }],
    'antfu/no-top-level-await': 'off',
    'prefer-arrow-callback': 'off',
    'no-unneeded-ternary': 'off',
    'one-var': 'off',
    'ts/prefer-namespace-keyword': 'off',
  },
})
